// this caters for both uuid4 suffixes generated by our internal topology tool and for _service-hash suffixes generated by eosc-connector
const SUFFIXES: readonly RegExp[] = [
  /_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
  /_service-[0-9A-Za-z]+$/,
]

export const stripIdSuffix = (name: string): string =>
  SUFFIXES.reduce((acc, pattern) => acc.replace(pattern, ''), name)
